#!/bin/bash

# Select a keyboard layout in a menu

outfile=${1:-/dev/stdout}
utilspath=/usr/lib/system-installer

. $utilspath/dialog-helper

trap "exit 1" SIGINT

dialog_helper --no-items --item-help --menu "Select your installation mode" 15 70 15 \
"basic" "Put the whole url of the image that you want to install." \
"custom" "Browse through the download.tizen.org directories and select the image that you want to install."

cat << EOC > $outfile
$(echo "$DIALOGRES")
EOC

exit 0
